---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Shangsi Lin
 206-605-1986 | sl5232@cumc.columbia.edu 
 
 50 Haven Ave, mailbox 200, New York, NY, 10032

## Educations
### University of Washington, 09/2018 ~ 06/2022

School of Arts and Sciences

Major in Biology with Concentration of Physiology

Overall GPA 3.67 out of 4.0

Bachelor of Science degree obtained in June 2022

Annual Dean’s list for 2018 – 2019; Dean’s list for Autumn 2019, Winter 2020, Autumn 2020, and Winter 2021

### Columbia University, 09/2022 ~ 06/2024
Mailman School of Public Health

MS Major in Biostatistics with Concentration of Public Health Data Science

## Experience 
### Project for Course Evolutionary and Ecological Physiology of Animals, 10/2021 ~ 11/2021
#### Investigating safezone and CT range changes across forest lizards living in different latitudes.
Reviewed 6 papers and multiple articles reporting on forest lizard, content related with their habitat, seasonality, and daily activity. Used programming in R to modify and construct data table on the foundation of existing data set obtained from previous research papersUsed programming in R to construct novel synthetic figure presenting correlation between the range of safezone and absolute latitude. Wrote a 3000 word report on the investigation, explaining the trend found and further discussed the possible magnitude of effect due to climate change on forest lizards living in different latitude according to the trend. 


### Internship at CDC of Weihai City, Shandong Province, 05/2021 ~ 08/2021
#### Worked in Public Health Inspection Department as field assistant.
Conducted site investigations with the staff.
Sent samples to the lab for testing of factors including Ion Concentration and Bacteriostatic Concentration
Sorted out testing results.
Checked results against standard values and reported abnormals to Supervisor.
Research Assistant in “2021 Wet Season Tap Water Inspection Report”.

#### Worked in Immune and Prevention Department as assistant.
Assumed liaison between the vaccine storehouse and hospitals to support vaccine distribution.
Provided consultancy to public individuals regarding vaccination.
Organized data and assisted in producing summary tables summarizing all vaccination facts across districts of the City.

### Project for Course Conservation Biology, 04/2021 ~ 06/2021
#### Making of whooping crane conservation (WCC) website
Reviewed nearly 20 papers on WCC and collected data.
Produced Novel Synthetic Figure by connecting whooping crane population with factors including Carbon emission, Habitat loss, and Hunting pressure.
Reached conclusions on the status of WCC and proposed future actions including wetland conservation.
Made website utilizing Wix.